# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=4)),
                ('model_name', models.CharField(max_length=15)),
                ('colour', models.CharField(max_length=10)),
                ('car_image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('variation_type', models.CharField(max_length=15)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.Car_model')),
            ],
        ),
    ]
